# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  head_nx_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  head_ny_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  head_nz_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  l_akx_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  l_aky_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  l_elx_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  l_ely_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  l_hpx_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  l_hpy_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  l_hpz_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  l_kny_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  l_shx_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  l_shy_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  l_wry_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  r_akx_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  r_aky_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  r_elx_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  r_ely_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  r_hpx_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  r_hpy_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  r_hpz_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  r_kny_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  r_shx_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0
  r_shy_joint:
    has_velocity_limits: true
    max_velocity: 7.48
    has_acceleration_limits: false
    max_acceleration: 0
  r_wry_joint:
    has_velocity_limits: true
    max_velocity: 5.817
    has_acceleration_limits: false
    max_acceleration: 0