# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - head_ny_joint
    - head_nz_joint
    - head_nx_joint
    - l_hpz_joint
    - l_hpx_joint
    - l_hpy_joint
    - l_kny_joint
    - l_aky_joint
    - l_akx_joint
    - l_shy_joint
    - l_shx_joint
    - l_ely_joint
    - l_elx_joint
    - l_wry_joint
    - r_hpz_joint
    - r_hpx_joint
    - r_hpy_joint
    - r_kny_joint
    - r_aky_joint
    - r_akx_joint
    - r_shy_joint
    - r_shx_joint
    - r_ely_joint
    - r_elx_joint
    - r_wry_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: rarm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r_shy_joint
      - r_shx_joint
      - r_ely_joint
      - r_elx_joint
      - r_wry_joint
  - name: larm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - l_shy_joint
      - l_shx_joint
      - l_ely_joint
      - l_elx_joint
      - l_wry_joint
  - name: head_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - head_ny_joint
      - head_nz_joint
      - head_nx_joint
  - name: rleg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - r_hpz_joint
      - r_hpx_joint
      - r_hpy_joint
      - r_kny_joint
      - r_aky_joint
      - r_akx_joint
  - name: lleg_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - l_hpz_joint
      - l_hpx_joint
      - l_hpy_joint
      - l_kny_joint
      - l_aky_joint
      - l_akx_joint
  - name: wholebody_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - head_ny_joint
      - head_nz_joint
      - head_nx_joint
      - l_hpz_joint
      - l_hpx_joint
      - l_hpy_joint
      - l_kny_joint
      - l_aky_joint
      - l_akx_joint
      - l_shy_joint
      - l_shx_joint
      - l_ely_joint
      - l_elx_joint
      - l_wry_joint
      - r_hpz_joint
      - r_hpx_joint
      - r_hpy_joint
      - r_kny_joint
      - r_aky_joint
      - r_akx_joint
      - r_shy_joint
      - r_shx_joint
      - r_ely_joint
      - r_elx_joint
      - r_wry_joint